# Generated by Django 6.0.3 on 2026-03-25 08:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=50, unique=True, verbose_name='N° Produit')),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='UAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UAP',
                'verbose_name_plural': 'UAP',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateField()),
                ('quantite_livree', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_bon_livraison', models.CharField(blank=True, max_length=100)),
                ('reference_commande', models.CharField(blank=True, max_length=100)),
                ('remarques', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='reclamations.client')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du programme')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='programmes', to='reclamations.client')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SiteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(blank=True, default='France', max_length=100)),
                ('contact_principal', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_client', to='reclamations.client')),
            ],
            options={
                'verbose_name': 'Site client',
                'verbose_name_plural': 'Sites clients',
                'ordering': ['client', 'nom'],
                'unique_together': {('nom', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(max_length=50, unique=True, verbose_name='N° Réclamation')),
                ('date_reclamation', models.DateField(default=django.utils.timezone.now)),
                ('imputation', models.CharField(choices=[('CIM', 'CIM'), ('CIB', 'CIB'), ('CLIENT', 'CLIENT'), ('ALERT', 'ALERT')], default='CIM', max_length=20, verbose_name='Imputation')),
                ('type_nc', models.CharField(choices=[('FOURNISSEUR', 'Fournisseur'), ('LOGISTIQUE', 'Logistique'), ('TRANSPORT', 'Transport'), ('TECHNIQUE', 'Technique')], default='TECHNIQUE', max_length=20, verbose_name='Type NC')),
                ('etat_4d', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20, verbose_name='État 4D')),
                ('etat_8d', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20, verbose_name='État 8D')),
                ('evidence', models.TextField(blank=True)),
                ('me', models.BooleanField(default=False, verbose_name='ME')),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('date_cloture_4d', models.DateField(blank=True, null=True)),
                ('date_cloture_8d', models.DateField(blank=True, null=True)),
                ('decision', models.TextField(blank=True)),
                ('nqc', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût NQC (MAD)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='reclamations.client')),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_crees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='reclamations.programme')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='reclamations.site')),
                ('site_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='reclamations.siteclient')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_reclamation', '-id'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='uap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='reclamations.uap'),
        ),
        migrations.CreateModel(
            name='ObjectifsAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2026, verbose_name='Année')),
                ('objectif_rebut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Objectif rebut (%)')),
                ('objectif_ppm_externe', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif PPM Externe')),
                ('objectif_rework', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Objectif Rework (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='reclamations.site')),
            ],
            options={
                'verbose_name': 'Objectif annuel',
                'verbose_name_plural': 'Objectifs annuels',
                'ordering': ['-annee', 'site__nom'],
                'unique_together': {('annee', 'site')},
            },
        ),
        migrations.CreateModel(
            name='LigneReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description_non_conformite', models.TextField(verbose_name='Description non-conformité')),
                ('commentaire', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reclamation', to='reclamations.produit')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reclamations.reclamation')),
                ('uap_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_reclamation', to='reclamations.uap')),
            ],
            options={
                'verbose_name': 'Ligne de réclamation',
                'verbose_name_plural': 'Lignes de réclamation',
                'unique_together': {('reclamation', 'produit')},
            },
        ),
    ]
