# Generated by Django 6.0.3 on 2026-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='numero_4d',
            field=models.CharField(blank=True, help_text='Numéro de la démarche 4D', max_length=50, null=True, verbose_name='N° 4D'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='numero_8d',
            field=models.CharField(blank=True, help_text='Numéro de la démarche 8D', max_length=50, null=True, verbose_name='N° 8D'),
        ),
    ]
